name: "dep-scan"
description: "dep-scan is a fully open-source security audit tool for project dependencies based on known vulnerabilities and advisories."
inputs:
  src:
    description: "Source directory to scan. Defaults to workspace"
    required: false
    default: "/github/workspace"
  report_file:
    description: "Output file for the generated report. Defaults to reports/depscan.json"
    required: false
    default: "/github/workspace/reports/depscan.json"
  bom:
    description: "Use the pre-built bom file instead of generating one"
    required: false
runs:
  using: "docker"
  image: "docker://ghcr.io/appthreat/dep-scan:master"
  args:
    - "--src"
    - ${{ inputs.src }}
    - "--report_file"
    - ${{ inputs.report_file }}
    - "--suggest"
branding:
  icon: "check"
  color: "blue"
